import { lusitana } from '@/app/ui/fonts';
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Test App Home',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col p-6">

      <h1 className='text-xl text-blue-700'>Title</h1>
      <p
      className={`${lusitana.className} text-xl text-gray-800 md:text-3xl md:leading-normal`}
      >
      <strong>Welcome to Acme.</strong> This is the example for the{' '}
      <a href="https://nextjs.org/learn/" className="text-blue-500">
        Next.js Learn Course
      </a>
      , brought to you by Vercel.
    </p>
    </main>
  )
}
